import type { Metadata } from "next";
import Link from "next/link";
import { SITE } from "@/lib/site";

export const metadata: Metadata = { title: `Terms and Conditions — ${SITE.name}`, description: "Terms for use of the BRIM Burgers website." };

export default function TermsPage() {
  return <LegalPage title="Terms and conditions" updated="15 September 2026"><p>These terms apply to your use of this website. They do not create a contract for food, delivery or franchise services.</p><LegalSection title="About us"><p>This website is operated for BRIM Burgers Ltd, a company registered in England and Wales (company number 12305135). Our registered office is {SITE.contact.address}.</p></LegalSection><LegalSection title="Using this website"><p>You may use this website for lawful, personal purposes. You must not interfere with its operation, attempt unauthorised access, introduce harmful code, or use its content in a way that infringes our rights or anyone else’s rights.</p></LegalSection><LegalSection title="Information on the website"><p>We aim to keep the information on this website current and accurate. Menus, ingredients, allergen information, prices, availability, restaurant hours and location details may change and can vary by restaurant. Please confirm important information directly with the relevant restaurant before relying on it.</p></LegalSection><LegalSection title="Third-party links"><p>This website may link to third-party services such as Google Maps, delivery platforms or a Google Form. Those services are governed by their own terms and privacy notices. We are not responsible for their content, availability or practices.</p></LegalSection><LegalSection title="Intellectual property"><p>The BRIM name, logo, website design, photography, video, text and other content are owned by, or licensed to, BRIM Burgers Ltd. You may not copy, reproduce, distribute or commercially use them without prior written permission, except where the law allows.</p></LegalSection><LegalSection title="Liability"><p>Nothing in these terms excludes or limits liability that cannot be excluded or limited under applicable law. To the extent permitted by law, we are not liable for loss arising from reliance on general website information, interruption of the website, or third-party websites and services.</p></LegalSection><LegalSection title="Changes and contact"><p>We may update these terms by publishing a revised version here. Questions about these terms can be sent to <a href={`mailto:${SITE.contact.email}`}>{SITE.contact.email}</a>.</p></LegalSection></LegalPage>;
}

function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) { return <main className="min-h-dvh bg-paper px-6 pb-20 pt-32 text-ink [color-scheme:light] sm:px-10"><article className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-bold uppercase tracking-wide underline-offset-4 hover:underline">← Back to BRIM</Link><h1 className="mt-10 font-display text-5xl uppercase leading-none sm:text-7xl">{title}</h1><p className="mt-5 text-sm text-ink/50">Last updated: {updated}</p><div className="mt-12 space-y-8 text-base leading-relaxed text-ink/70">{children}</div></article></main>; }
export function LegalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="font-display text-2xl uppercase leading-none text-ink sm:text-3xl">{title}</h2><div className="mt-3 space-y-4">{children}</div></section>; }
